### ISSUE TITLE
Bug - Error in List Inactive Enterprise Apps 

### ISSUE THREAD

**Issue by cekageka** [realmjoin/realmjoin-runbooks#102]
<img width="886" alt="Screenshot 2022-09-17 at 23 22 25" src="https://user-images.githubusercontent.com/1116271/190876857-f2f53cbc-2da9-491f-8e41-114f48b4b6bb.png">

**Comment by hcoberdalhoff** [comment]
Can not reproduce the issue. Are you sure, the MS Graph "app" permissions are in place?
Recommended: "Directory.Read.All" (as used by other runbooks).
See https://learn.microsoft.com/en-us/graph/api/serviceprincipal-get?view=graph-rest-1.0&tabs=http for more options.

Please reopen if something else is of.
