### ISSUE TITLE
Backlog - Duplicate group with members

### ISSUE THREAD

**Issue by schwerdti** [realmjoin/realmjoin-runbooks#103]
For switching from on-premises/synched groups to cloud only groups it would be great to have a copy function for groups with the following options:

- selection of existing group
- new name of copied group
- checkboxes (one or multiple selections possible): migrate users/migrate devices/migrate groups
- checkbox: copy owner yes/no

**Comment by hcoberdalhoff** [comment]
Ok, this is more of a RJ Portal Feature topic IMHO. Let's talk.

**Comment by hcoberdalhoff** [comment]
But the Runbook part: Just "Duplicate an existing (hybrid) group as cloud only group, optionally with members copied" is added to the backlog.

**Comment by hcoberdalhoff** [comment]
Directly available in RJ Portal now
