### ISSUE TITLE
Automatic upload of Corporate device identifiers

### ISSUE THREAD

**Issue by bastigade** [realmjoin/realmjoin-runbooks#104]
To not upload corporate device identifiers (IMEI or serial number of mobile devices) manually, a runbook would be great.

![ci](https://user-images.githubusercontent.com/120113727/206474513-ecfd81f0-b5fb-4eaa-b764-aa9cf02b9691.png)

https://learn.microsoft.com/en-us/answers/questions/635712/is-there-graph-api-to-enroll-corporate-device-iden.html

**Comment by hcoberdalhoff** [comment]
Hi,

have a look at https://github.com/realmjoin/realmjoin-runbooks/blob/master/org/general/add-device-via-corporate-identifier.ps1 
:)
