### ISSUE TITLE
Backlog - Block users from viewing BitLocker key

### ISSUE THREAD

**Issue by schwerdti** [realmjoin/realmjoin-runbooks#105]
Would be cool to offer this script as small runbook:
[Block users from viewing their BitLocker keys](https://learn.microsoft.com/en-us/azure/active-directory/devices/device-management-azure-portal#block-users-from-viewing-their-bitlocker-keys-preview)

**Comment by hcoberdalhoff** [comment]
Ok, taken into the backlog (no garanty though ;)) - Let's talk with Alex and Karsten

**Comment by schwerdti** [comment]
Available via Entra portal.
