### ISSUE TITLE
Show BitLocker recovery keys for device

### ISSUE THREAD

**Issue by schwerdti** [realmjoin/realmjoin-runbooks#111]
Due to viewing BitLocker keys is often restricted users might contact the helpdesk for the BitLocker recovery key.
Would be good to have a runbook (on devices) that shows stored BitLocker keys.

**Comment by schwerdti** [comment]
Graph Calls:

1. Get list of all **BitLocker keys and their IDs** for specific AAD device:
[Retrieve a list of BitLocker keys filtered by deviceId](https://learn.microsoft.com/en-us/graph/api/bitlocker-list-recoverykeys?view=graph-rest-1.0#example-2-retrieve-a-list-of-bitlocker-keys-filtered-by-deviceid)

2. Get the **BitLocker key with the key** property (using ID/s from step 1):
[Get the BitLocker key with the key property](https://learn.microsoft.com/en-us/graph/api/bitlockerrecoverykey-get?view=graph-rest-1.0#example-2-get-the-bitlocker-key-with-the-key-property)

**Comment by hcoberdalhoff** [comment]
Moved to backlog

**Comment by hcoberdalhoff** [comment]
Implemented 9139768 by (available in master branch currently)

**Comment by hcoberdalhoff** [comment]
Hi,

MS Graph does not allow access "as app" to Bitlocker keys, see
https://learn.microsoft.com/en-us/graph/api/bitlockerrecoverykey-get?view=graph-rest-1.0

I had hoped it works anyway, but nope it doesn't. Sorry, can not implement as runbook.

**Comment by schwerdti** [comment]
@hcoberdalhoff Seems that this is possible meanwhile:
https://learn.microsoft.com/en-us/graph/api/bitlockerrecoverykey-get?view=graph-rest-1.0&tabs=http#permissions

![image](https://github.com/user-attachments/assets/cec29003-df6d-45e4-a7de-74ca04c59a73)
