### ISSUE TITLE
Resource intensive queries should be avoided

### ISSUE THREAD

**Issue by marcoscheel** [realmjoin/realmjoin-runbooks#75]
The following implementation to check a group membership is very resource intense and should be simplefied:

https://github.com/realmjoin/realmjoin-runbooks/blob/179cb2b91c5d167ba0ebe42a40bfa6f1b0c0e5d2/user/general/assign-license.ps1#L37

Try to check the user ID/UPN is a member or walk the user path and check the membership:

My user is not member of the group and will result in a 404
```
https://graph.microsoft.com/v1.0/groups/013dd0eb-eba5-4ccc-bffd-e1eadbc1e8dd/members/11c6d408-3a58-4367-9b5d-60ba1cf3594a

{
    "error": {
        "code": "Request_ResourceNotFound",
        "message": "Resource '013dd0eb-eba5-4ccc-bffd-e1eadbc1e8dd' does not exist or one of its queried reference-property objects are not present.",
        "innerError": {
            "date": "2021-06-22T06:41:55",
            "request-id": "54ec78e8-c555-4340-84e2-1a17801d752c",
            "client-request-id": "90b324a1-b52b-46ed-74fc-bc1dbd430c0b"
        }
    }
}
```

Alternative route:
https://graph.microsoft.com/v1.0/users/marco.scheel@glueckkanja-gab.com/memberOf/013dd0eb-eba5-4ccc-bffd-e1eadbc1e8dd

**Comment by hcoberdalhoff** [comment]
Implemented the change. Will checkt other runbook for this pattern. Thanks!
