### ISSUE TITLE
Extend 'Add Remove Trusted Site' and 'Add Remove SafeLinks Exclusion'

### ISSUE THREAD

**Issue by cekageka** [realmjoin/realmjoin-runbooks#80]
Please extend the Runbook to be more fail safe:

a) please add an (default on) option to 'Use Default Policy' so admin does not need to name the policy
a) please add a 'List current Safelinks' option
d) if possible, please enumerate an existing default policy
e) if no default policy is available, please create one with SafeLinks Default Policy Name: *Default Policy*

@hcoberdalhoff

**Comment by hcoberdalhoff** [comment]
Please review https://github.com/realmjoin/realmjoin-runbooks/blob/master/org/general/add-or-remove-safeLinks-exclusion.ps1
