### ISSUE TITLE
Extend 'Add Remove Trusted Site'

### ISSUE THREAD

**Issue by cekageka** [realmjoin/realmjoin-runbooks#81]
Please extend the Runbook to be more fail safe:

a) please clone the output schema from SafeLinks to TrustedSites to be more detailed in output
b) please add an (default on) option to 'Use Default Policy' so admin does not need to name the policy
c) please add a 'List current TrustedSites' option (and subsequently remove the 'List Trusted Sites' Runbook)
d) if possible, please enumerate an existing default policy

Please ask @okieselbach for a good guess on TrustedSite Default Policy Name.

@hcoberdalhoff

**Comment by cekageka** [comment]
Hi @hcoberdalhoff, seems like 'list trusted sites' (related to this ticket, that's why I re-open) has no response. Tested in two tenants.
![Screenshot 2021-12-16 at 15 45 40](https://user-images.githubusercontent.com/1116271/146393339-de7f5297-5e33-47a7-9e5f-9c34bc1425ca.png)

**Comment by cekageka** [comment]
Maybe also combining it with add/remove like in safelinks?  
  
![Screenshot 2021-12-16 at 15 48 30](https://user-images.githubusercontent.com/1116271/146393643-174856da-eb80-4e4d-bd5b-1b486f76fc24.png)

**Comment by hcoberdalhoff** [comment]
> Hi @hcoberdalhoff, seems like 'list trusted sites' (related to this ticket, that's why I re-open) has no response. Tested in two tenants.

Ok, this is correct if not fitting policies are present. Will add an explaining output for the "empty" case. Thanks!

Also, merging the runbooks sounds good.

**Comment by hcoberdalhoff** [comment]
Check a0c783b408248424089fc442b97f259fe04e0551

**Comment by hcoberdalhoff** [comment]
@cekageka close?
