### ISSUE TITLE
New Runbook: Add Remove SmartScreen Sites

### ISSUE THREAD

**Issue by cekageka** [realmjoin/realmjoin-runbooks#82]
a) please clone functionality from TrustedSites (and the output schema from SafeLinks)
b) please add an (default on) option to 'Use Default Policy' so admin does not need to name the policy
c) please add a 'List current SmartScreen Sites' option
d) if possible, please enumerate an existing default policy
  
Please ask @okieselbach for a good guess on Default Policy Name.
  
@hcoberdalhoff
  
Links:  
https://www.inthecloud247.com/configure-microsoft-defender-smartscreen-to-block-potentially-unwanted-apps-with-microsoft-intune/

**Comment by cekageka** [comment]
Ticket seems orphaned?

**Comment by hcoberdalhoff** [comment]
Implemented by https://github.com/realmjoin/realmjoin-runbooks/blob/master/org/general/add-or-remove-smartscreen-exclusion.ps1
