### ISSUE TITLE
Split Table in 'List Inactive Users' in Members / Guests

### ISSUE THREAD

**Issue by cekageka** [realmjoin/realmjoin-runbooks#83]
We may add the attribute in the main list or split the output into two tables for better visibility.

**Comment by hcoberdalhoff** [comment]
see 059d346d772b47e295691f41741bcb4b0bb44c31
available in master

**Comment by cekageka** [comment]
One more thing: Would make sense to add a column DISABLED.

**Comment by hcoberdalhoff** [comment]
I am already building something similiar - a switch to exclude blocked users (careful: "disabled users" can get you in trouble with political correctness in a UI - no joke)

**Comment by hcoberdalhoff** [comment]
But sure, I can also include another column

**Comment by hcoberdalhoff** [comment]
see 335e0246226a4cd513c473073d4c1e68cab01a99 in master
