### ISSUE TITLE
Remove Email Alias not working

### ISSUE THREAD

**Issue by cekageka** [realmjoin/realmjoin-runbooks#84]
Tried with two email proxy adresses, both times the runbook ended with success but nothing changed. Images edited bc of privacy.
  
<img width="845" alt="Screenshot 2021-11-29 at 16 50 43" src="https://user-images.githubusercontent.com/1116271/143899999-14f10432-deac-4b76-ba75-28f1d6094cdf.png">

**Comment by hcoberdalhoff** [comment]
Thank you for finding this bug :)

Fixed in master, see c78eed4f98d682c27a5ec39ed1d08efc9019fab8

Will push to production
