### ISSUE TITLE
Remove Group Output

### ISSUE THREAD

**Issue by cekageka** [realmjoin/realmjoin-runbooks#85]
Remove Group  
(https://github.com/realmjoin/realmjoin-runbooks/blob/eae21b32b1453e41b76d1ee58fdcbfe5e09a90f5/group/general/remove-group.ps1) 
  
is showing the mail nickname when deleting a group. This is quite confusing, see attached pictures - it may get people to be very uncertain if the correct group was deleted. Please use the Name instead.
  
![Screenshot 2021-11-29 at 17 01 22](https://user-images.githubusercontent.com/1116271/143901571-96c13551-4710-4388-b417-ae353cb83088.png)
  

<img width="845" alt="Screenshot 2021-11-29 at 16 58 11" src="https://user-images.githubusercontent.com/1116271/143901589-2860dccd-d789-41f6-94b3-95593710c08f.png">

**Comment by hcoberdalhoff** [comment]
Fixed in master branch
![1](https://user-images.githubusercontent.com/78223857/143999753-3a218ef1-15db-4c2f-b500-530cf53b1e32.png)
![2](https://user-images.githubusercontent.com/78223857/143999775-2bc32525-4c1f-4a0b-bf0c-6066ff57cda0.png)
by 419dc19c96bcd2de7855b42aa3c06ecfa827b01b

**Comment by cekageka** [comment]
hm... also ich hab da keinen displayname:
 
![Screenshot 2021-12-01 at 12 53 26](https://user-images.githubusercontent.com/1116271/144229970-acd3cb6e-c676-4cae-83f6-470c1d526f44.png)

**Comment by cekageka** [comment]
mein fehler
