### ISSUE TITLE
Remove Licenses and Remove Group Option for User Out-Phase

### ISSUE THREAD

**Issue by cekageka** [realmjoin/realmjoin-runbooks#86]
Runbook:  
https://github.com/realmjoin/realmjoin-runbooks/blob/master/user/general/offboard-user-temporarily.ps1 and  
https://github.com/realmjoin/realmjoin-runbooks/blob/master/user/general/offboard-user-permanently.ps1
  
Please check internal Thread:  
https://teams.microsoft.com/l/message/19:b27c626453e448a7bd3bdc6208803c4b@thread.tacv2/1638372912897?tenantId=a53834b7-42bc-46a3-b004-369735c3acf9&groupId=4ccd3815-3f60-4776-a37b-3036b8be9fd5&parentMessageId=1638372912897&teamName=GKGAB%20Tech%20Community&channelName=Workplace&createdTime=1638372912897
  
Please remove the 'sample' Strings if possible, should be empty or set bei tenant config. The license groups need configuration and we can't always expect that this config is done. But because out-phasing should help getting licenses free anyhow we should offer an alternative switch for 

> Remove all licences

which actively removes all licenses. 

In addition - especially because of license groups - we should also add an option to remove the user from all groups:
  
> Remove from all groups

**Comment by hcoberdalhoff** [comment]
Hi, 
have a look at "offboard user temporarily", commits
2d1be79067170012bf15f899d5802ff2ff327407 and
b8bb1f6114835c69e02dca8457011604a9f4e919

- moved to MS Graph API (away from AzureAD module)
- supports directly assigned lics (not only groups)
- option to remove all groups

I will adapt these changes to "offboard user permanently".

**Comment by hcoberdalhoff** [comment]
Applied the same to "offboard user permanently", see ac627efb340a470a63d52990aad375239437eeb4

**Comment by cekageka** [comment]
Had no chance to check so far, just a short question because it's a typical problem:  
  
> option to remove all groups
  
Do you check for dynamic groups? You cant remove one here....

**Comment by hcoberdalhoff** [comment]
Thank you for catching the dyn. group issue!
Fixed in 4b7630e7bb7aba8db1532581bbe4a88611eb46b9
