### ISSUE TITLE
Bug in Outphase Device

### ISSUE THREAD

**Issue by cekageka** [realmjoin/realmjoin-runbooks#87]
Not sure why, but 'disable' device seems to fail.
  
![Screenshot 2022-01-31 at 11 10 43 copy](https://user-images.githubusercontent.com/1116271/151841354-f79bd41c-f55b-457f-88c1-48dc4565bdcc.png)

**Comment by hcoberdalhoff** [comment]
This seems to be a bug/weirdness in MS Graph API behaviour. 

When auth. "delegated" (as User), it works. If authed "as App" it only works on windows devices. Probably some filtering is done wrong.

I updated our runbooks accordingly and will try to reach out to MS.

Will post here, when I push the changes.

**Comment by hcoberdalhoff** [comment]
Pushed 6f67d4e9e3d813da1e4bd32f42a66b1f0d5911e9

**Comment by hcoberdalhoff** [comment]
Posted https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/updating-a-device-in-ms-graph-using-app-permissions-vs-delegated/idi-p/3098295

**Comment by cekageka** [comment]
@hcoberdalhoff close?

**Comment by hcoberdalhoff** [comment]
looking for a place to retest 😅

**Comment by cekageka** [comment]
Ticket seems orphaned?

**Comment by hcoberdalhoff** [comment]
No update from MS or in the forums. Will retest functionality.

**Comment by hcoberdalhoff** [comment]
Still broken on MS Side. The runbook evades this for now. - Sorry, can not do more here.
