### ISSUE TITLE
Owner needs to be a Member too

### ISSUE THREAD

**Issue by marcoscheel** [realmjoin/realmjoin-runbooks#93]
For several M365 group features like Planner it is required to have all owner also added as a member.

https://github.com/realmjoin/realmjoin-runbooks/blob/e4377cbae43252390211db0ba7527ba1df27fca4/org/general/add-office365-group.ps1#L109

**Comment by hcoberdalhoff** [comment]
Fixed by 9bf06584421365cbe994da6d905bf6ae27bb0885

**Comment by hcoberdalhoff** [comment]
Thanks! Did find a bug through this :)

**Comment by marcoscheel** [comment]
@hcoberdalhoff gerade ist aufgefallen, dass du nicht die eigentliche Anfrage (Create Group) gefixst hast sondern "nur" dass add/remove member runbook. Bei der WinDea wird aber oft das Create Group verwendet und wir laufen reihenweise in Bugs weil teams und co damit nicht klar kommt.

Kannst du das bitte nochmal fixen? Hatte die Code Zeile hier im Issue verlinkt.

Danke

**Comment by hcoberdalhoff** [comment]
Jetzt aber. Danke und Sorry.
fixed by a73397007afce682f4957fe631372daeb36de0b8
