### ISSUE TITLE
MFA reset still not working for OATH tokens

### ISSUE THREAD

**Issue by marcoscheel** [realmjoin/realmjoin-runbooks#96]
https://github.com/realmjoin/realmjoin-runbooks/blob/f6e74a262d86c29031a080c1f295da8d2ade3dd7/user/security/reset-mfa.ps1#L49

This is likely a copy paste error. The fido line is not correct with the double assignment. And I can confirm it is not working in production.

**Comment by hcoberdalhoff** [comment]
fixed by #97
